<?php

namespace Circle314\Component\Data\Persistence\Operation\Cache\Database;

use \PDOStatement;
use Circle314\Component\Data\Persistence\Operation\Cache\QueryInterface;

interface DatabaseQueryInterface extends QueryInterface
{
    /**
     * The PDOStatement that is generated by the prepared statement of the query.
     * @return PDOStatement
     */
    public function PDOStatement();
}